services:
  # --- SERVICE WEB DJANGO ---
  - type: web
    name: django-backend
    env: python
    plan: professional
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
